import { Header } from '@/components/Header';
import { Provider } from '@/context/Provider';
import { Box } from '@/utils/chakra';
import type { Metadata } from 'next';
import { Hanken_Grotesk } from 'next/font/google';

const haken = Hanken_Grotesk({
  subsets: ['latin'],
  weight: ['500'],
});
export const metadata: Metadata = {
  title: 'Wormscan',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={haken.className}>
        <Provider>
          <Header />
          <Box>{children}</Box>
        </Provider>
      </body>
    </html>
  );
}
